14-implement-authentication
kalex375/game-queue pull request #16
Opened 2022-09-17 13:29 UTC by DanMir0

2022-09-17 17:08 UTC, kalex375 requested changes
![image](https://user-images.githubusercontent.com/966329/190868388-35507a5d-90db-4dc7-93fd-b21b8b5eeafe.png)

В случае успеха API  будет возвращать тебе данные пользователя их нужно где-то сохранять чтобы например выводить его профиль.

Если ты добавил Remember me то нужно тогда его и реализовывать это тоже часть этой задачи.

Также Logout это тоже часть этой задачи.

2022-09-17 17:08 UTC, kalex375 commented on src/hooks/useLoginUser.js
> +        routers.push({name: 'dashboard'})
В общем случае compossible не должен перенаправлять на другую страницу, он должен возвращать либо true либо false. А уже компонент  который его используют будет решать что делать дальше. Либо показывать ошибк либо либо перенаправлять на другую страницу.

2022-09-17 17:08 UTC, kalex375 commented on src/hooks/useLoginUser.js
> +        alert('Неверный пароль или логин!')
На каком ты сайте видел чтобы неправильный логин пароль выводились через Alert? мы пишем не учебный код а вполне реальный

2022-09-17 17:55 UTC, DanMir0 commented
т.е. создать новую функцию создать в компоненте которая получает true или
false и от этого и исходя из этого перенапрвлять на страницу или на этой же
оставляться?

сб, 17 сент. 2022 г., 20:08 Oleksandr Kravchenko ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> [image: image]
> <https://user-images.githubusercontent.com/966329/190868388-35507a5d-90db-4dc7-93fd-b21b8b5eeafe.png>
>
> В случае успеха API будет возвращать тебе данные пользователя их нужно
> где-то сохранять чтобы например выводить его профиль.
>
> Если ты добавил Remember me то нужно тогда его и реализовывать это тоже
> часть этой задачи.
>
> Также Logout это тоже часть этой задачи.
> ------------------------------
>
> In src/router/router.js
> <https://github.com/kalex375/game-queue/pull/16#discussion_r973606580>:
>
> > @@ -27,6 +27,11 @@ const routes = [
>          name: 'reset-password',
>          component: () => import('@/pages/CreateNewPasswordPage.vue'),
>      },
> +    {
> +        path: '/dashboard',
>
> Я могу попасть на эту страницу если наберу её в браузере не используя
> пароль.
> http://localhost:8083/dashboard
>
> Нужно сделать так чтобы на странице которые под паролем нельзя было
> попасть если пользователь не прошёл аутентификацию
> ------------------------------
>
> In src/hooks/useLoginUser.js
> <https://github.com/kalex375/game-queue/pull/16#discussion_r973606951>:
>
> > -        password: '123',
> -        email: ''
> -    },
> -    {
> -        id: 2,
> -        username: 'Alex',
> -        password: '123',
> -        email: ''
> -    },
> -]
> -
> +import routers from "@/router/router";
> +
> +export async function useLoginUser(email, password) {
> +    if (email === ***@***.***' && password === 'admin1') {
> +        routers.push({name: 'dashboard'})
>
> В общем случае compossible не должен перенаправлять на другую страницу, он
> должен возвращать либо true либо false. А уже компонент который его
> используют будет решать что делать дальше. Либо показывать ошибк либо либо
> перенаправлять на другую страницу.
> ------------------------------
>
> In src/hooks/useLoginUser.js
> <https://github.com/kalex375/game-queue/pull/16#discussion_r973607178>:
>
> > -    },
> -    {
> -        id: 2,
> -        username: 'Alex',
> -        password: '123',
> -        email: ''
> -    },
> -]
> -
> +import routers from "@/router/router";
> +
> +export async function useLoginUser(email, password) {
> +    if (email === ***@***.***' && password === 'admin1') {
> +        routers.push({name: 'dashboard'})
> +    } else {
> +        alert('Неверный пароль или логин!')
>
> На каком ты сайте видел чтобы неправильный логин пароль выводились через
> Alert? мы пишем не учебный код а вполне реальный
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kalex375/game-queue/pull/16#pullrequestreview-1111453388>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW2T5MAE3EHIAQJ2TT6NBV3V6X3JBANCNFSM6AAAAAAQPAID74>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-17 18:44 UTC, kalex375 commented
Попробуй для начала всю логику написать в компоненте. То есть создавать все
функции которые тебе нужны в твоём loginform setup. не используя внешние
use...
Я запустил Pocket Bass на севере поэтому этот запрос уже будет возвращать
данные


```
import PocketBase from 'pocketbase'

const client = new PocketBase('http://game-queue.com:8888');

const userData = await ***@***.***',
'admin1admin1');
```


вс, 18 сент. 2022 г. в 00:55, DanMir0 ***@***.***>:

> т.е. создать новую функцию создать в компоненте которая получает true или
> false и от этого и исходя из этого перенапрвлять на страницу или на этой
> же
> оставляться?
>
> сб, 17 сент. 2022 г., 20:08 Oleksandr Kravchenko ***@***.***>:
>
> > ***@***.**** requested changes on this pull request.
> >
> > [image: image]
> > <
> https://user-images.githubusercontent.com/966329/190868388-35507a5d-90db-4dc7-93fd-b21b8b5eeafe.png>
>
> >
> > В случае успеха API будет возвращать тебе данные пользователя их нужно
> > где-то сохранять чтобы например выводить его профиль.
> >
> > Если ты добавил Remember me то нужно тогда его и реализовывать это тоже
> > часть этой задачи.
> >
> > Также Logout это тоже часть этой задачи.
> > ------------------------------
> >
> > In src/router/router.js
> > <https://github.com/kalex375/game-queue/pull/16#discussion_r973606580>:
> >
> > > @@ -27,6 +27,11 @@ const routes = [
> > name: 'reset-password',
> > component: () => import('@/pages/CreateNewPasswordPage.vue'),
> > },
> > + {
> > + path: '/dashboard',
> >
> > Я могу попасть на эту страницу если наберу её в браузере не используя
> > пароль.
> > http://localhost:8083/dashboard
> >
> > Нужно сделать так чтобы на странице которые под паролем нельзя было
> > попасть если пользователь не прошёл аутентификацию
> > ------------------------------
> >
> > In src/hooks/useLoginUser.js
> > <https://github.com/kalex375/game-queue/pull/16#discussion_r973606951>:
> >
> > > - password: '123',
> > - email: ''
> > - },
> > - {
> > - id: 2,
> > - username: 'Alex',
> > - password: '123',
> > - email: ''
> > - },
> > -]
> > -
> > +import routers from "@/router/router";
> > +
> > +export async function useLoginUser(email, password) {
> > + if (email === ***@***.***' && password === 'admin1') {
> > + routers.push({name: 'dashboard'})
> >
> > В общем случае compossible не должен перенаправлять на другую страницу,
> он
> > должен возвращать либо true либо false. А уже компонент который его
> > используют будет решать что делать дальше. Либо показывать ошибк либо
> либо
> > перенаправлять на другую страницу.
> > ------------------------------
> >
> > In src/hooks/useLoginUser.js
> > <https://github.com/kalex375/game-queue/pull/16#discussion_r973607178>:
> >
> > > - },
> > - {
> > - id: 2,
> > - username: 'Alex',
> > - password: '123',
> > - email: ''
> > - },
> > -]
> > -
> > +import routers from "@/router/router";
> > +
> > +export async function useLoginUser(email, password) {
> > + if (email === ***@***.***' && password === 'admin1') {
> > + routers.push({name: 'dashboard'})
> > + } else {
> > + alert('Неверный пароль или логин!')
> >
> > На каком ты сайте видел чтобы неправильный логин пароль выводились через
> > Alert? мы пишем не учебный код а вполне реальный
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/kalex375/game-queue/pull/16#pullrequestreview-1111453388>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AW2T5MAE3EHIAQJ2TT6NBV3V6X3JBANCNFSM6AAAAAAQPAID74>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kalex375/game-queue/pull/16#issuecomment-1250114807>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHL5OIVGY5DM3TCONLCHTLV6YA2VANCNFSM6AAAAAAQPAID74>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-09-17 18:46 UTC, kalex375 commented
Попробуй для начала всю логику написать в компоненте. То есть создавать все
функции которые тебе нужны в твоём loginform setup. не используя внешние
use...
Я запустил Pocket Bass на севере поэтому этот запрос уже будет возвращать
данные

```
import PocketBase from 'pocketbase'


const client = new PocketBase('http://game-queue.com:8888/');

const userData = await client.users.authViaEmail('admin@tv.tv', 'admin1admin1');

```

2022-09-17 18:59 UTC, kalex375 commented
https://watch.screencastify.com/v/i9YeTAX7PsVDadE8fvPh

2022-09-21 19:52 UTC, kalex375 requested changes

2022-09-21 19:52 UTC, kalex375 commented on src/components/LoginForm.vue
> +        <GqButton @click="signIn">Sign In</GqButton>
вообще правильно вешать обработчик на форм сабмит раз ты ее добавил

2022-09-21 19:52 UTC, kalex375 commented on src/components/LoginForm.vue
> +        message.value = 'The user is not registered in the system.'
мы не знаем есть такой пользователь или нет. правильно писать что неверный логин и пароль

2022-09-21 19:52 UTC, kalex375 commented on src/router/router.js
> +    console.log(to.matched);
дебаг коде нужно удалять

2022-09-21 19:52 UTC, kalex375 commented on src/router/router.js
> +        if (localStorage.getItem('TOKEN_USER')) {
нет, пока нужно проверять что есть user.token    из хука. локал сторадж нам пока не нужен. client     сам пишет туда потом переделаем на проверку из  client

2022-09-22 11:56 UTC, kalex375 approved these changes

2022-09-22 12:02 UTC, merged