31 Fix login page styles
kalex375/game-queue pull request #34
Opened 2022-09-26 18:30 UTC by rexx0n

2022-09-26 19:21 UTC, kalex375 commented
![image](https://user-images.githubusercontent.com/966329/192362025-45edbd18-cc4a-4f44-a2c1-384a006c3f6d.png)

2022-09-27 12:35 UTC, kalex375 requested changes
![image](https://user-images.githubusercontent.com/966329/192527731-91d891ae-7df3-4c97-895f-c6abcc38df13.png)

 зачем у кнопок margin?

2022-09-27 13:00 UTC, kalex375 commented
Отступы между элементами не равны

2022-09-27 13:04 UTC, rexx0n commented
кнопки тоже укорачивать?

2022-09-27 13:05 UTC, kalex375 commented
Да

2022-09-27 14:37 UTC, kalex375 requested changes

2022-09-27 14:37 UTC, kalex375 commented on src/components/LoginForm.vue
> +    gap: 2rem;
Дело не в гап. Просто растени по боками justify space between

2022-09-27 14:37 UTC, kalex375 commented on src/components/LoginForm.vue
> +    padding: 15px 20px;
Нам не нужен класс. Нужно уменьшить у комнпанета button padding и поставить min Wight

2022-09-27 14:37 UTC, kalex375 commented on src/components/LoginForm.vue
>  .btn-bg {
Мы работаем с вуи поэтому здесь все компонеты. Нужно создать компонет кнопку gqbuttongoogle на основе gqbutton и там добавть эти стили.

И вообще классы лучше так не называть типо btn padding или btn bg. Название должно что то говорить. Типо btn-blue или btn-google или btn small. Ты бы на русском  бы не дал бы название кнопка-фон. Что фон?

2022-09-27 14:37 UTC, kalex375 commented on src/components/LoginForm.vue
> +    font-size: 15px;
Я на компе не проверял, но в том макете что я скинул я рпзмер шрифта не трогал

2022-09-27 14:37 UTC, kalex375 commented on src/components/LoginForm.vue
> +            <!-- <p :v-text="message">{{ message }}</p> -->
Не будет надписи что неверный логин пароль. Чтобы скрыть элемент нужно использовать директиву v-if="!message"

2022-09-27 14:37 UTC, kalex375 commented on src/components/LoginForm.vue
> +            <div class="login">
Зачем нужен этот div?

2022-09-27 15:07 UTC, rexx0n commented on src/components/LoginForm.vue
> +    gap: 2rem;
![image](https://user-images.githubusercontent.com/95697161/192564035-a2e9772f-7ac7-4d72-9c4d-acad6be73a3a.png)

2022-09-27 15:09 UTC, kalex375 commented on src/components/LoginForm.vue
> +    gap: 2rem;
Ну растяни контейнер 100%

2022-09-27 15:11 UTC, rexx0n commented on src/components/LoginForm.vue
> +    gap: 2rem;
забыл поставить width 100%

2022-09-27 15:26 UTC, kalex375 requested changes
Почти)

2022-09-27 15:26 UTC, kalex375 commented on src/components/LoginForm.vue
> +            <GqButtonGoogle class="btn-bg">SIGN IN WITH GOOGLE</GqButtonGoogle>
Зачем нам нуженкласс btn bg

2022-09-27 15:26 UTC, kalex375 commented on src/components/UI/GqButtonGoogle.vue
> +    border-color: #3464b3;
Мы падинги уменьшаем у базаой кнопи и ставим min-wigth:130px

2022-09-27 15:26 UTC, kalex375 commented on src/components/LoginForm.vue
>      width: 100%;
Это можно перенести в gqinput. Их почти всегда нужно растягивать на 100%

2022-09-27 15:28 UTC, kalex375 requested changes

2022-09-27 15:28 UTC, kalex375 commented on src/components/LoginForm.vue
> +    min-width: 97px;
Зачем это?

2022-09-27 15:38 UTC, kalex375 approved these changes

2022-09-27 15:41 UTC, merged