37 Add 404 page
kalex375/game-queue pull request #39
Opened 2022-09-28 16:32 UTC by rexx0n

2022-09-28 17:14 UTC, kalex375 requested changes

2022-09-28 17:14 UTC, kalex375 commented on src/pages/NotFound.vue
> +            <router-link :to="{name: 'sign-in'}"
or router-link with class btn or button with @click
now you get "button inside a"

2022-09-28 17:14 UTC, kalex375 commented on src/pages/NotFound.vue
> +        <div>
why need this div?

2022-09-28 18:27 UTC, rexx0n commented on src/pages/NotFound.vue
> +        <div>
To align everything in the center

2022-09-29 15:03 UTC, kalex375 commented on src/pages/NotFound.vue
>      text-decoration: none;
ну это наверное должно быть в общих свойствах кнопки

2022-09-29 15:19 UTC, VerVera approved these changes

2022-09-29 15:25 UTC, merged