32 Create header
kalex375/game-queue pull request #41
Opened 2022-09-30 14:26 UTC by rexx0n

2022-09-30 15:31 UTC, VerVera requested changes
Зделай его раза в полтора уже., сильно большой

2022-09-30 15:31 UTC, VerVera commented on src/components/UI/GqHeader.vue
> +    background-image: url('https://templatekit.tokokoo.com/knight/wp-content/uploads/sites/17/2021/01/navbar-bg.jpg');
Картинки должены быть у тебя в проекте, это не очень хорошо использовать с чужого сервера. Их к примеру могут удаить.

2022-09-30 15:31 UTC, VerVera commented on src/main.js
> +import GqHeader from '@/components/UI/GqHeader'
Пожалуй это уже не ui компанент. Я бы его просто в components

2022-09-30 15:31 UTC, VerVera commented on src/components/UI/GqHeader.vue
> +    flex-direction: column;
Зачем это?  Где указано что этот флекс

2022-09-30 15:31 UTC, VerVera commented on src/components/UI/GqHeader.vue
> +    display: flex;
У тебя все div буду флексами. Это фигня. Давай классы. Я так почитал все пишут что скопед фигня и судя по тому что у нас прлучается это правда.

2022-09-30 15:31 UTC, VerVera commented on src/components/UI/GqHeader.vue
> +                <p>username</p>
У тебя в dashboard  есть пример как вывести email реальный. Кто будет писать логику компонентов

2022-10-02 09:59 UTC, kalex375 requested changes

2022-10-02 09:59 UTC, kalex375 commented on src/components/UI/GqHeader.vue
> +                <a class="username" href="profile">{{ user.email }}</a>
Просто нужно положить в одну ссылку и картинку и текст

2022-10-02 14:25 UTC, kalex375 approved these changes

2022-10-02 14:34 UTC, merged