we need to fix it #57
kalex375/game-queue pull request #58
Opened 2022-10-12 13:33 UTC by DanMir0

2022-10-12 13:46 UTC, VerVera requested changes

2022-10-12 13:46 UTC, VerVera commented on src/router/router.js
> +        name: 'add-game',
Где мета о том что этот роут доступен только авторизации

2022-10-13 07:41 UTC, VerVera requested changes

2022-10-13 07:41 UTC, VerVera commented on src/hooks/useGameList.js
> +    onMounted(getGames, showGames)
Что это за строчка и что она делает?

2022-10-15 17:43 UTC, kalex375 approved these changes

2022-10-19 15:33 UTC, merged